import 'package:jiffy/jiffy.dart';

class Script {
  int id; // ID of the script
  String name; // Name of the script
  String? description;
  String outputType; // bar_chart || line_chart
  String outputName; // Display name of the value

  Script.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'],
        description = map['description'],
        outputType = map['output_type'],
        outputName = map['output_name'];

  Script(
      this.id, this.name, this.description, this.outputType, this.outputName);
}

class OutputValue {
  dynamic value; // The output value
  int timestamp; // Timestamp for when the value was generated

  OutputValue(this.value, this.timestamp);
}

class ScriptOutput {
  int id; // ID of the script output
  Script script; // The script that generated the output
  List<OutputValue> values =
      []; // List of output values generated by the script

  ScriptOutput.fromMap(Map<String, dynamic> map, Script _script)
      : id = map['id'],
        script = _script;

  ScriptOutput(this.id, this.script, this.values);
}

class TeamModel {
  int id;
  String name;
  // CoachModel? coach;
  List<TeamMemberModel> teamMembers = List.empty(growable: true);

  TeamModel.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'],
        teamMembers = createTeamMembersList(map['team_members']);

  TeamModel(this.id, this.name);
}

class CoachModel {
  int id;
  String name;

  CoachModel(this.id, this.name);
}

class TeamMemberModel {
  int id;
  String name;

  TeamMemberModel.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'];

  TeamMemberModel(this.id, this.name);
}

List<TeamMemberModel> createTeamMembersList(List<dynamic> list) {
  return list.map((member) => TeamMemberModel.fromMap(member)).toList();
}

class Session {
  int id;
  String name;
  Jiffy startedAt;
  Jiffy endedAt;

  Session.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'],
        startedAt = Jiffy(map['started_at']),
        endedAt = Jiffy(map['ended_at']);

  Session(this.id, this.name, this.startedAt, this.endedAt);
}
